
- type: Program Commitee Member
  type_zh: 程序委员会委员
  venue: ACM Conference on Interactive User Interfaces
  year: 2025

- type: Program Commitee Member
  type_zh: 程序委员会委员
  venue: IEEE Pacific Visualization Symposium (Notes)
  year: 2024

- type: Reviewer
  type_zh: 期刊审稿人
  venue: IEEE Transactions on Visualization and Computer Graphics

- type: Reviewer
  type_zh: 期刊审稿人
  venue: Visual Informatics

- type: Reviewer
  type_zh: 期刊审稿人
  venue: Journal of Computer-Aided Design & Computer Graphics


- type: Reviewer
  type_zh: 期刊审稿人
  venue: Computer Graphics Forum

- type: Reviewer
  type_zh: 期刊审稿人
  venue: Journal of Visualization

- type: Reviewer
  type_zh: 审稿人
  venue: ACM Conference on Human Factors in Computing Systems
  year: 2025

- type: Reviewer
  type_zh: 审稿人
  venue: ACM Conference on Interactive User Interfaces
  year: 2025

- type: Reviewer
  type_zh: 审稿人
  venue: IEEE Visualization Conference
  year: 2024


- type: Reviewer
  type_zh: 审稿人
  venue: ACM Conference on Human Factors in Computing Systems
  year: 2024

- type: Reviewer
  type_zh: 审稿人
  venue: ACM Symposium on User Interface Software and Technology
  year: 2024

- type: Reviewer
  type_zh: 审稿人
  venue: IEEE Visualization Conference
  year: 2023

- type: Reviewer
  type_zh: 审稿人
  venue: ACM Conference on Human Factors in Computing Systems
  year: 2023

- type: Reviewer
  type_zh: 审稿人
  venue: IEEE Visualization Conference
  year: 2022

- type: Reviewer
  type_zh: 审稿人
  venue: IEEE Visualization Conference
  year: 2021

- type: Reviewer
  type_zh: 审稿人
  venue: ACM Conference on Human Factors in Computing Systems
  year: 2021


- type: Reviewer
  type_zh: 审稿人
  venue: IEEE Visualization Conference
  year: 2020

- type: Reviewer
  type_zh: 审稿人
  venue: IEEE Pacific Visualization Symposium
  year: 2020


- type: Reviewer
  type_zh: 审稿人
  venue: China Visualization and Visual Analytics Conference
  year: 2020


- type: Reviewer
  type_zh: 审稿人
  venue: IEEE Visualization Conference (Short Paper)
  year: 2019

- type: Reviewer
  type_zh: 审稿人
  venue: China Visualization and Visual Analytics Conference
  year: 2019

- type: Student Volunteer
  type_zh: 学生志愿者
  venue: China Visualization and Visual Analytics Conference
  year: 2021

- type: Student Volunteer
  type_zh: 学生志愿者
  venue: China Visualization and Visual Analytics Conference
  year: 2020

- type: Student Volunteer
  type_zh: 学生志愿者
  venue: IEEE Visualization Conference
  year: 2019
