(() => {
  const chapters = {
    51: {
      number: "五一", label: "第五十一章", hero: "生而不有，<br><em>长而不宰。</em>", heroEn: "Give life without possessing; nurture without ruling over.",
      deck: "真正的培育，是让生命长出自己的方向。", deckEn: "True cultivation allows life to grow a direction of its own.",
      originalTitle: "道生之，德畜之", originalTitleEn: "The Dao Gives Life; Virtue Nurtures",
      original: `道生之，德畜之，物形之，势成之。<br>是以万物莫不尊道而贵德。<br>道之尊，德之贵，夫莫之命，而常自然。<br><br>故道生之，德畜之；长之育之；亭之毒之；养之覆之。<br>生而不有，为而不恃，长而不宰。<br>是谓玄德。`,
      originalEn: "The Dao gives life; virtue nurtures; matter gives form; conditions bring maturity. All things honor the Dao and value virtue—not by command, but naturally. The Dao gives life and virtue raises, grows, shelters, matures, nourishes, and protects. It gives life without possessing, acts without relying on achievement, and nurtures without ruling. This is profound virtue.",
      explainTitle: "成长需要帮助，也需要不被占有", explainTitleEn: "Growth Needs Support—and Freedom from Possession",
      explain: [["一棵树离不开土地、阳光、雨水与照料，但没有一种条件可以宣布：它必须长成我的样子。第五十一章写的是生成性的力量：做了许多，却不把贡献变成对生命的所有权。", "A tree needs soil, sunlight, rain, and care, yet none may declare that it must grow in its image. Chapter 51 describes generative power: doing much without turning contribution into ownership of life."], ["“莫之命而常自然”尤其重要。稳固的秩序，不是每一刻都靠命令维持，而是条件、能力与关系已经让合适的行动自然发生。", "“Not by command, but naturally” is crucial. Stable order does not require commands every moment; conditions, capability, and relationships make appropriate action arise on its own."]],
      storyTitle: "文翁兴学：让人成长，不把人占有", storyTitleEn: "Wen Weng Builds a School: Let People Grow Without Possessing Them", image: "chapter-51-1.png", imageAlt: "文翁在蜀地兴办学堂，哆啦A梦与大雄理解长而不宰", caption: "提供生长的条件，不把成长据为己有。", captionEn: "Provide the conditions for growth without claiming growth as property.",
      story: [["《汉书·循吏传》记文翁任蜀郡太守，见蜀地教育不足，便选年轻人受业，兴办学官。后来当地教化大兴，人才渐多。", "The Book of Han records that Wen Weng, governor of Shu, saw the region’s lack of educational opportunity, selected young people for study, and established a school. Learning flourished and local talent grew."], ["学校最好的成果，不是让学生永远依赖创办者，而是让他们获得继续教人、做事和判断的能力。培育者退到一旁，生长才真正属于生命自己。", "A school succeeds not by making students permanently dependent on its founder, but by giving them the capacity to teach, act, and judge. When the cultivator can step aside, growth belongs to the growing life."]],
      guardTitle: "“不宰”不是放任，也不是取消责任", guardTitleEn: "Not Ruling Over Is Neither Neglect nor Abdication", guard: [["老子列出的“长之、育之、养之、覆之”全是具体工作。不给控制权，不等于不给资源、反馈与边界；先把条件做好，才不必用持续干预证明自己重要。", "Laozi lists concrete work: growing, raising, nourishing, and protecting. Refusing control does not mean withholding resources, feedback, or boundaries. Sound conditions make constant intervention unnecessary."]],
      closeTitle: "最好的帮助，最后会让帮助者不再必要", closeTitleEn: "The Best Help Eventually Makes the Helper Unnecessary", close: "给他根，不替他决定枝叶；<br>给他路，不要求每一步都回头致谢。", closeEn: "Give roots without dictating every branch; give a path without demanding thanks at every step.", final: "让生命生长，<br><em>不把生命据为己有。</em>", finalEn: "Nurture life without possessing it.",
      sources: [["《道德经》王弼本", "https://zh.wikisource.org/zh-hans/%E9%81%93%E5%BE%B7%E7%B6%93_%28%E7%8E%8B%E5%BC%BC%E6%9C%AC%29"], ["《汉书·循吏传》", "https://zh.wikisource.org/zh-hans/%E6%BC%A2%E6%9B%B8/%E5%8D%B7089"]]
    },
    52: {
      number: "五二", label: "第五十二章", hero: "见小曰明，<br><em>守柔曰强。</em>", heroEn: "Seeing the small is clarity; keeping to gentleness is strength.",
      deck: "真正的明，不只看见已经发生的大事，也看见还来得及改变的小兆头。", deckEn: "Clarity sees not only large events already formed, but small signs while change is still possible.",
      originalTitle: "既知其子，复守其母", originalTitleEn: "Know the Branches, Return to the Source",
      original: `天下有始，以为天下母。<br>既得其母，以知其子；既知其子，复守其母，没身不殆。<br>塞其兑，闭其门，终身不勤；开其兑，济其事，终身不救。<br><br>见小曰明，守柔曰强。<br>用其光，复归其明，无遗身殃。<br>是为习常。`,
      originalEn: "The world has a beginning, which may be called its mother. Knowing the mother, one understands the children; knowing the children, one returns to guard the mother and remains secure. Close the openings and one is not exhausted; multiply them and one cannot be rescued. To see the small is clarity; to keep to gentleness is strength. Use the light, return to illumination, and leave no harm behind. This is practicing the constant.",
      explainTitle: "不要等问题变大，才承认它存在", explainTitleEn: "Do Not Wait for a Problem to Grow Before Admitting It Exists",
      explain: [["“母”是使许多现象得以出现的根本条件，“子”是我们看见的具体结果。只追着结果奔忙，容易终身不救；回到源头，才能减少问题不断再生。", "The mother is the underlying condition from which many appearances arise; the children are the visible outcomes. Chasing outcomes alone creates endless rescue work. Returning to the source reduces recurrence."], ["见小并不是多疑，而是对早期信号保持敏感：一个反复出现的小错误、一段关系中的轻微紧张、身体持续发出的异常，都值得在代价还小时认真检查。", "Seeing the small is not paranoia. It is sensitivity to early signals: a recurring small error, slight tension in a relationship, or a persistent bodily warning deserves attention while the cost remains low."]],
      storyTitle: "扁鹊见蔡桓公：小处不看，大处难救", storyTitleEn: "Bian Que and Duke Huan: Ignore the Small, and the Large Becomes Hard to Save", image: "chapter-52-1.png", imageAlt: "扁鹊观察蔡桓公的细小病兆，哆啦A梦说明见小曰明", caption: "看见小处，才来得及守住大处。", captionEn: "See the small while there is still time to protect the whole.",
      story: [["《韩非子·喻老》借扁鹊见蔡桓公解释“图难于其易，为大于其细”。病在腠理时容易处理，桓公却不肯承认；等它一步步深入，能采取的办法也越来越少。", "Han Feizi uses Bian Que’s visits to Duke Huan to explain handling difficulty while it is easy and greatness while it is small. The illness is manageable near the surface, but denial lets it deepen until options disappear."], ["故事的重点不在古代医学细节，而在决策结构：早期信号往往最不体面，因为承认它意味着承认自己可能错了；正是这份不体面，保留了修正的空间。", "The point is not ancient medical detail but decision structure. Early signals feel embarrassing because acknowledging them means admitting possible error; that small embarrassment preserves room for correction."]],
      guardTitle: "见小不是把每个小事都灾难化", guardTitleEn: "Seeing the Small Does Not Mean Catastrophizing Everything", guard: [["早期判断也会出错，所以要观察趋势、寻找证据、请合适的人复核。明不是紧张地预言最坏结果，而是在信号与代价之间保持比例。", "Early judgments can be wrong, so observe trends, gather evidence, and seek appropriate review. Clarity does not anxiously predict the worst; it keeps signal and response in proportion."]],
      closeTitle: "光要用来照见根，不只是追逐影子", closeTitleEn: "Use Light to See the Root, Not Merely Chase Shadows", close: "大问题很少在一夜之间长成；<br>只是小问题常被我们一再略过。", closeEn: "Large problems rarely grow in one night; small ones are simply passed over again and again.", final: "见其小，<br><em>守其本。</em>", finalEn: "See the small; guard the source.",
      sources: [["《道德经》王弼本", "https://zh.wikisource.org/zh-hans/%E9%81%93%E5%BE%B7%E7%B6%93_%28%E7%8E%8B%E5%BC%BC%E6%9C%AC%29"], ["《韩非子·喻老》", "https://ctext.org/hanfeizi/illustrations-of-lao-tzu/zh"]]
    },
    53: {
      number: "五三", label: "第五十三章", hero: "大道甚夷，<br><em>而民好径。</em>", heroEn: "The great way is level, yet people prefer shortcuts.",
      deck: "捷径最危险的时候，是它把排场的成本悄悄交给别人。", deckEn: "A shortcut is most dangerous when the cost of display is quietly handed to others.",
      originalTitle: "朝甚除，田甚芜", originalTitleEn: "The Court Is Splendid While the Fields Lie Waste",
      original: `使我介然有知，行于大道，唯施是畏。<br>大道甚夷，而民好径。<br><br>朝甚除，田甚芜，仓甚虚；<br>服文采，带利剑，厌饮食，财货有余。<br>是谓盗夸。<br>非道也哉！`,
      originalEn: "If I possessed the least understanding, I would walk the great way and fear only straying from it. The great way is level, yet people prefer shortcuts. The court is splendid while fields are overgrown and granaries empty. Fine clothes, sharp swords, excessive food, and surplus wealth—this is robber’s pomp. It is not the Dao.",
      explainTitle: "真正的偏离，常被装饰成繁荣", explainTitleEn: "Deviation Is Often Decorated as Prosperity",
      explain: [["老子把两幅画并排放在一起：一边是整洁华丽的朝廷，一边是荒芜的田与空虚的仓。问题不在美本身，而在光鲜是否建立在生产、民生和公共能力被抽空之上。", "Laozi places two pictures side by side: a splendid court and neglected fields with empty granaries. Beauty is not the problem. The issue is whether display is built by hollowing out production, livelihood, and public capacity."], ["“好径”不是反对效率。真正的捷径，是绕过责任、把收益留给自己、把成本转给别人。路看起来短了，社会却要走更长的路来偿还。", "The critique of shortcuts is not a rejection of efficiency. A false shortcut bypasses responsibility, keeps gains private, and transfers costs to others. The route looks shorter while society must travel farther to repay it."]],
      storyTitle: "汉文帝罢露台：不拿民生为排场让路", storyTitleEn: "Emperor Wen Cancels the Terrace: Do Not Sacrifice Livelihood to Display", image: "chapter-53-1.png", imageAlt: "汉文帝得知露台需百金后停止工程，哆啦A梦与大雄观看", caption: "大路不难，难的是不走炫耀的捷径。", captionEn: "The great way is not difficult; refusing the shortcut of display is.",
      story: [["《史记·孝文本纪》记汉文帝想建露台，工匠估价百金。他得知这相当于十户中等人家的产业，便说“何以台为”，停止工程。", "The Records of the Grand Historian says Emperor Wen considered building a terrace. When told it would cost one hundred jin—roughly the property of ten ordinary households—he asked why he needed it and canceled the project."], ["这个决定没有把一切建设都叫作浪费，而是把一项象征性工程重新放回公共资源的尺度上衡量：它带来的价值，是否值得别人承担的成本？", "The decision did not condemn all construction as waste. It returned a symbolic project to the scale of public resources and asked whether its value justified the cost others would bear."]],
      guardTitle: "节制公共排场，不等于拒绝公共建设", guardTitleEn: "Limiting Display Does Not Mean Rejecting Public Investment", guard: [["道路、水利、教育与公共空间也需要资源。区别不在花不花钱，而在受益者是谁、代价由谁承担、工程是否解决真实问题，以及能否接受公开检验。", "Roads, waterworks, schools, and public spaces require resources. The distinction is not spending versus saving, but who benefits, who pays, whether a real problem is solved, and whether the project survives public scrutiny."]],
      closeTitle: "先看田与仓，再看台与殿", closeTitleEn: "Look First at Fields and Granaries, Then at Terraces and Halls", close: "繁华若抽空了承载繁华的人，<br>就只是把亏空装饰得更亮。", closeEn: "If splendor hollows out the people who sustain it, it merely decorates the deficit.", final: "大道不远，<br><em>只是排场常挡在路上。</em>", finalEn: "The great way is near; display often blocks it.",
      sources: [["《道德经》王弼本", "https://zh.wikisource.org/zh-hans/%E9%81%93%E5%BE%B7%E7%B6%93_%28%E7%8E%8B%E5%BC%BC%E6%9C%AC%29"], ["《史记·孝文本纪》", "https://zh.wikisource.org/zh-hant/%E5%8F%B2%E8%A8%98/%E5%8D%B7010"]]
    },
    54: {
      number: "五四", label: "第五十四章", hero: "善建者不拔，<br><em>善抱者不脱。</em>", heroEn: "What is well established cannot be uprooted; what is well held does not slip away.",
      deck: "能长久的秩序，不只写在牌匾上，也写进每天的习惯里。", deckEn: "An enduring order is written not only on plaques, but into daily habits.",
      originalTitle: "从修身，到天下", originalTitleEn: "From the Self to the World",
      original: `善建者不拔，善抱者不脱，子孙以祭祀不辍。<br><br>修之于身，其德乃真；修之于家，其德乃余；<br>修之于乡，其德乃长；修之于邦，其德乃丰；<br>修之于天下，其德乃普。<br><br>故以身观身，以家观家，以乡观乡，以邦观邦，以天下观天下。<br>吾何以知天下然哉？以此。`,
      originalEn: "What is well established cannot be uprooted; what is well held does not slip away, and remembrance continues through generations. Cultivate it in the self and virtue becomes genuine; in the family, abundant; in the community, enduring; in the state, rich; in the world, universal. Observe the self through the self, the family through the family, and the world through the world. How do I know the world is so? By this.",
      explainTitle: "规模不是跳过去的，而是一层层长出来的", explainTitleEn: "Scale Is Not Leaped Into; It Grows Layer by Layer",
      explain: [["第五十四章没有从宏大口号直接跳到天下，而从身体、家庭、乡里一路展开。一个原则若在自己身上都不能实行，放大以后往往只会放大矛盾。", "Chapter 54 does not jump from a grand slogan straight to the world. It moves through self, family, community, and state. A principle that cannot be practiced in oneself often magnifies contradiction when scaled."], ["“以身观身”也意味着尊重不同层级自身的尺度。不能只用管理国家的方式管理家庭，也不能用一个人的经验替整个天下下结论。", "Observing each level through itself means respecting its own scale. A family should not be governed exactly like a state, and one person’s experience cannot stand in for the whole world."]],
      storyTitle: "《诫子书》：能传下去的，是每天的做法", storyTitleEn: "The Admonition to a Son: What Endures Is Daily Practice", image: "chapter-54-1.png", imageAlt: "诸葛亮写诫子书，哆啦A梦与大雄理解修之于身", caption: "能传下去的，不是口号，是日常里的做法。", captionEn: "What can be passed on is not a slogan, but a daily way of living.",
      story: [["诸葛亮在《诫子书》中写“静以修身，俭以养德”，没有给儿子一张通往成功的捷径，而把根落在宁静、节俭、学习与志向这些日常选择上。", "In the Admonition to His Son, Zhuge Liang writes, “Through stillness cultivate the self; through frugality nourish virtue.” He offers no shortcut to success, but roots life in daily choices of calm, thrift, learning, and purpose."], ["家风若只剩祖先的名声，很容易一代而尽；若进入吃饭、读书、待人、用钱与承担责任的方式，才可能成为“善建者不拔”。", "A family tradition reduced to ancestral reputation may vanish in one generation. When it enters eating, reading, relationships, spending, and responsibility, it may become something well rooted and hard to uproot."]],
      guardTitle: "传承不是要求下一代复制上一代", guardTitleEn: "Inheritance Does Not Require One Generation to Copy the Last", guard: [["真正可传的不是固定职业、性格或人生剧本，而是面对变化时仍有用的能力与原则。根要稳，枝叶可以向不同方向生长。", "What deserves transmission is not a fixed occupation, personality, or life script, but abilities and principles that remain useful under change. Roots may be stable while branches grow in different directions."]],
      closeTitle: "先让原则在最近的地方成为真的", closeTitleEn: "Make the Principle Real at the Nearest Scale First", close: "不是先治理天下，再回来整理自己；<br>是从自己做得到的地方，长出更大的秩序。", closeEn: "Do not govern the world first and return later to the self; grow a larger order from what can be practiced here.", final: "根在日常，<br><em>德才可能走得很远。</em>", finalEn: "Root virtue in daily life, and it may travel far.",
      sources: [["《道德经》王弼本", "https://zh.wikisource.org/zh-hans/%E9%81%93%E5%BE%B7%E7%B6%93_%28%E7%8E%8B%E5%BC%BC%E6%9C%AC%29"], ["诸葛亮《诫子书》", "https://zh.wikisource.org/zh-hans/%E8%AA%A1%E5%AD%90%E6%9B%B8"]]
    },
    55: {
      number: "五五", label: "第五十五章", hero: "知和曰常，<br><em>知常曰明。</em>", heroEn: "To know harmony is to know the constant; to know the constant is clarity.",
      deck: "真正的强，不是一直绷紧，而是内在协调以后仍有余力。", deckEn: "Real strength is not permanent tension, but spare capacity created by inner coordination.",
      originalTitle: "含德之厚，比于赤子", originalTitleEn: "One Rich in Virtue Is Like a Newborn",
      original: `含德之厚，比于赤子。<br>毒虫不螫，猛兽不据，攫鸟不搏。<br>骨弱筋柔而握固；未知牝牡之合而朘作，精之至也；<br>终日号而不嗄，和之至也。<br><br>知和曰常，知常曰明。<br>益生曰祥，心使气曰强。<br>物壮则老，谓之不道；不道早已。`,
      originalEn: "One rich in virtue is like a newborn: bones weak and tendons soft, yet the grasp is firm; crying all day without becoming hoarse, the harmony is complete. To know harmony is to know the constant; to know the constant is clarity. Forcing life is ominous; making vital energy obey the mind is strain. What grows overhard soon ages. This is not the Dao, and what is not the Dao ends early.",
      explainTitle: "柔软与有力，可以同时存在", explainTitleEn: "Softness and Strength Can Exist Together",
      explain: [["婴儿的身体柔软，握力却很牢；声音持续，并非因为一直咬紧，而是呼吸、身体与需要尚未彼此冲突。老子借赤子说明的不是幼稚，而是未被过度用力破坏的协调。", "A newborn’s body is soft while its grasp is firm; its voice continues not through constant clenching, but because breath, body, and need have not been driven into conflict. The infant represents coordination unbroken by excessive force, not childishness."], ["“心使气曰强”警惕的是意志无限压迫身体。短期可以靠紧绷冲过去，长期却会把活力变成消耗。物壮则老，过度壮盛本身已带着衰退。", "The warning about mind forcing energy concerns limitless domination of the body by will. Tension may carry us through briefly, but over time turns vitality into depletion. Excessive vigor already contains decline."]],
      storyTitle: "木鸡：真正的强，不被挑衅牵走", storyTitleEn: "The Wooden Rooster: Strength No Longer Pulled by Provocation", image: "chapter-55-1.png", imageAlt: "纪渻子训练斗鸡如木鸡，哆啦A梦说明知和曰常", caption: "真正的强，不再被每一次挑衅牵走。", captionEn: "Real strength is no longer pulled by every provocation.",
      story: [["《庄子·达生》写纪渻子为周宣王训练斗鸡。十日后，鸡仍虚骄而恃气；再过十日，仍会被声影触动。直到四十日，它望之似木鸡，别的鸡见了便退走。", "Zhuangzi tells of Ji Shengzi training a rooster for King Xuan. After ten days it remains vain and aggressive; later it still reacts to sounds and shadows. After forty days it appears like a wooden bird, and other roosters withdraw without a fight."], ["故事不是赞美斗鸡，而是借训练过程说明：最初的强到处证明自己，成熟的强不需要被每一个刺激启动。稳定不是压抑，而是力量已经回到整体协调。", "The story does not praise animal fighting. It uses training to show that immature strength proves itself everywhere, while mature strength need not be activated by every stimulus. Stability is not suppression; force has returned to coordination."]],
      guardTitle: "像赤子，不等于拒绝经验与判断", guardTitleEn: "Being Like a Newborn Does Not Mean Rejecting Experience", guard: [["成年人不可能回到无知状态。可学习的是减少多余紧张、恢复感受与行动之间的联系，而不是把天真当作免于负责的理由。", "Adults cannot return to ignorance. What can be learned is reducing unnecessary tension and restoring connection between perception and action—not using innocence as an excuse to avoid responsibility."]],
      closeTitle: "力量不是越硬越多，而是越和越久", closeTitleEn: "Strength Does Not Grow by Hardening, but Endures Through Harmony", close: "不必让每一口气都服从焦虑的命令；<br>能松下来，力量才回得来。", closeEn: "Not every breath must obey anxiety; when tension releases, strength can return.", final: "柔而能握，<br><em>静而有力。</em>", finalEn: "Soft enough to hold; still enough to be strong.",
      sources: [["《道德经》王弼本", "https://zh.wikisource.org/zh-hans/%E9%81%93%E5%BE%B7%E7%B6%93_%28%E7%8E%8B%E5%BC%BC%E6%9C%AC%29"], ["《庄子·达生》", "https://ctext.org/zhuangzi/full-understanding-of-life/zh"]]
    },
    56: {
      number: "五六", label: "第五十六章", hero: "和其光，<br><em>同其尘。</em>", heroEn: "Soften the glare; join the dust of the world.",
      deck: "不熄灭自己的光，也不拿光去刺伤别人。", deckEn: "Do not extinguish your light, and do not use it to wound others.",
      originalTitle: "知者不言，言者不知", originalTitleEn: "Those Who Know Do Not Rush to Speak",
      original: `知者不言，言者不知。<br>塞其兑，闭其门；挫其锐，解其纷；<br>和其光，同其尘，是谓玄同。<br><br>故不可得而亲，不可得而疏；<br>不可得而利，不可得而害；<br>不可得而贵，不可得而贱。<br>故为天下贵。`,
      originalEn: "Those who know do not rush to speak; those who merely speak do not know. Close the openings, blunt the sharpness, untangle the knots, soften the glare, and join the dust. This is mysterious sameness. Such a person cannot be captured by intimacy or distance, benefit or harm, honor or disgrace, and is therefore valued by the world.",
      explainTitle: "有分量，不必总把锋芒放在外面", explainTitleEn: "Substance Need Not Keep Its Edge Exposed",
      explain: [["“知者不言”不是禁止有知识的人发言，而是说真正的理解知道语言的边界。复杂之处不能靠一句漂亮结论封死，未知之处也不必用自信语气遮住。", "“Those who know do not speak” is not a ban on knowledgeable speech. Understanding recognizes the limits of language. Complexity cannot be sealed by a polished sentence, and uncertainty need not be hidden behind confidence."], ["和光同尘也不是装傻。光仍然存在，只是收去刺眼的部分；人与普通生活站在一起，于是知识能够被听见，而不是先把别人压低。", "Softening the glare is not pretending ignorance. The light remains while its blinding edge is removed. Standing within ordinary life allows knowledge to be heard without first diminishing others."]],
      storyTitle: "老子见孔子：有光而不刺眼", storyTitleEn: "Laozi Meets Confucius: Light Without Glare", image: "chapter-56-1.png", imageAlt: "老子与孔子相见，哆啦A梦和大雄理解和光同尘", caption: "不熄灭自己的光，也不拿光去刺伤别人。", captionEn: "Do not extinguish your light or use it to wound others.",
      story: [["《史记·老子韩非列传》写孔子问礼于老子。临别时，老子以“良贾深藏若虚，君子盛德容貌若愚”相劝：真正有货的商人不把宝物全摆在门口，真正有德的人也不靠外表时时证明。", "The Records of the Grand Historian tells of Confucius consulting Laozi. Laozi advises him that a good merchant hides treasures and appears empty, while a person of deep virtue may appear plain rather than constantly displaying worth."], ["深藏若虚不是故弄玄虚，而是知道展示本身也有成本。少一点自我证明，注意力才可能回到对方、问题和共同世界。", "Appearing empty is not deliberate mystification. Display itself has a cost. With less self-proof, attention can return to the other person, the problem, and the shared world."]],
      guardTitle: "谦和不能变成故意含糊", guardTitleEn: "Humility Must Not Become Deliberate Vagueness", guard: [["需要公开证据、明确责任和指出伤害时，沉默并不高明。和光同尘是改变表达的姿态，不是逃避应说的话；锋芒可以收，原则不能丢。", "When evidence, responsibility, or harm must be stated, silence is not wisdom. Softening the glare changes the manner of expression; it does not evade what must be said. The edge may be sheathed without losing principle."]],
      closeTitle: "让知识进入世界，而不是站在世界上面", closeTitleEn: "Let Knowledge Enter the World Rather Than Stand Above It", close: "真正的光照见别人，<br>不需要先让别人睁不开眼。", closeEn: "True light helps others see; it need not blind them first.", final: "有光，<br><em>却不以耀眼为目的。</em>", finalEn: "Have light without making glare the goal.",
      sources: [["《道德经》王弼本", "https://zh.wikisource.org/zh-hans/%E9%81%93%E5%BE%B7%E7%B6%93_%28%E7%8E%8B%E5%BC%BC%E6%9C%AC%29"], ["《史记·老子韩非列传》", "https://zh.wikisource.org/zh-hant/%E5%8F%B2%E8%A8%98/%E5%8D%B7063"]]
    },
    57: {
      number: "五七", label: "第五十七章", hero: "我无事，<br><em>而民自富。</em>", heroEn: "I do not overburden affairs, and the people prosper themselves.",
      deck: "规则应当成为护栏，而不是用繁密证明权力存在。", deckEn: "Rules should serve as guardrails, not prove power through density.",
      originalTitle: "法令滋彰，盗贼多有", originalTitleEn: "As Laws Multiply, Evasion Multiplies",
      original: `以正治国，以奇用兵，以无事取天下。<br>吾何以知其然哉？以此：<br><br>天下多忌讳，而民弥贫；人多利器，国家滋昏；<br>人多伎巧，奇物滋起；法令滋彰，盗贼多有。<br><br>故圣人云：我无为而民自化；我好静而民自正；<br>我无事而民自富；我无欲而民自朴。`,
      originalEn: "Govern the state with regularity, use surprise in war, and win the world through freedom from meddling. The more prohibitions, the poorer the people; the more instruments of advantage, the more confused the state; the more clever schemes, the more strange distortions arise; the more laws are proclaimed, the more thieves appear. Therefore: I do not force, and the people transform themselves; I value stillness, and they correct themselves; I create no burdens, and they prosper; I am without grasping desire, and they return to simplicity.",
      explainTitle: "制度越复杂，不一定越能抵达目标", explainTitleEn: "More Complex Rules Do Not Necessarily Reach the Goal",
      explain: [["规则最初用于保护人和协调行动；若不断增加到没人能理解，人们便把精力从解决问题转向研究怎样符合表面要求。治理看起来更精细，真实情况反而更难回来。", "Rules begin by protecting people and coordinating action. When they multiply beyond understanding, effort shifts from solving problems to satisfying appearances. Governance looks more precise while reality becomes harder to hear."], ["“无事”不是政府消失，而是减少反复扰动：标准稳定、权责清楚、底线可执行，让人能够安排生活和生产，不必天天猜下一条命令。", "Freedom from meddling does not mean government disappears. It reduces repeated disturbance: stable standards, clear authority, and enforceable boundaries let people plan life and work without guessing the next command."]],
      storyTitle: "约法三章：规则回到护人", storyTitleEn: "Three Simple Laws: Return Rules to Protection", image: "chapter-57-1.png", imageAlt: "刘邦入关约法三章，哆啦A梦与大雄理解法令滋彰", caption: "规则是护栏，不是用繁密证明权力。", captionEn: "Rules are guardrails, not a display of power through complexity.",
      story: [["《史记·高祖本纪》写刘邦入关后，废除秦代繁密法令，与关中父老约法三章，保护生命、身体和财产。百姓知道基本边界，恐惧随之减轻。", "The Records of the Grand Historian says that after entering the pass, Liu Bang abolished Qin’s dense laws and agreed with local elders on three basic protections for life, body, and property. Clear boundaries reduced fear."], ["约法三章不足以构成完整现代法治，却提供一个重要对照：制度的价值不在条文数量，而在普通人能否理解、权力是否受约束、受伤害者是否得到真实保护。", "Three laws are not a complete modern rule of law, but they offer a useful contrast. Institutional value lies not in the number of clauses, but in public intelligibility, constrained power, and real protection from harm."]],
      guardTitle: "少规则，不等于少保护", guardTitleEn: "Fewer Rules Must Not Mean Less Protection", guard: [["劳动、安全、隐私和反歧视等复杂问题需要清楚规则。老子的警告针对的是重复、矛盾、朝令夕改与只为检查而存在的条文，不是让强者在模糊中随意决定。", "Complex issues such as labor, safety, privacy, and discrimination require clear rules. Laozi warns against duplication, contradiction, constant change, and rules that exist only for inspection—not against protecting people from arbitrary power."]],
      closeTitle: "好制度让人把注意力还给生活", closeTitleEn: "Good Institutions Return Attention to Life", close: "规则够清楚，人便不必天天研究规则；<br>边界够稳定，行动才有生长的空间。", closeEn: "When rules are clear, people need not study them all day; when boundaries are stable, action has room to grow.", final: "少一点扰动，<br><em>多一点真实秩序。</em>", finalEn: "Less disturbance; more genuine order.",
      sources: [["《道德经》王弼本", "https://zh.wikisource.org/zh-hans/%E9%81%93%E5%BE%B7%E7%B6%93_%28%E7%8E%8B%E5%BC%BC%E6%9C%AC%29"], ["《史记·高祖本纪》", "https://zh.wikisource.org/zh-hant/%E5%8F%B2%E8%A8%98/%E5%8D%B7008"]]
    },
    59: {
      number: "五九", label: "第五十九章", hero: "治人事天，<br><em>莫若啬。</em>", heroEn: "In governing people and serving nature, nothing surpasses conservation.",
      deck: "啬不是不出手，而是把力量积到真正需要的时候。", deckEn: "Conservation is not refusal to act; it stores strength for the moment that truly needs it.",
      originalTitle: "深根固柢，长生久视", originalTitleEn: "Deep Roots and a Firm Foundation",
      original: `治人事天，莫若啬。<br>夫唯啬，是谓早服；早服谓之重积德。<br>重积德则无不克；无不克则莫知其极；<br>莫知其极，可以有国；有国之母，可以长久。<br>是谓深根固柢，长生久视之道。`,
      originalEn: "In governing people and serving nature, nothing surpasses conservation. Conservation means preparing early; preparing early means repeatedly accumulating virtue. Deep accumulation can meet every challenge, and its limit cannot be known. With such a foundation, a state can endure. This is called deep roots, a firm base, and the way of long life and lasting vision.",
      explainTitle: "把余量留在系统里", explainTitleEn: "Keep Spare Capacity Inside the System",
      explain: [["“啬”不是吝啬，而是珍惜、收敛与不过度消耗。体力、财政、信用、注意力和生态承载力都需要余量；若每次都用到极限，下一次变化到来时便没有选择。", "Here, conservation is not stinginess but care, restraint, and refusal of overuse. Health, finance, trust, attention, and ecological capacity all require reserves. Use everything to the limit, and the next change leaves no options."], ["“早服”把准备放到危机之前，“重积德”则说明可靠不是一次英雄行动，而是许多次小的正确选择累积成的信用与能力。", "Early preparation places readiness before crisis. Repeated accumulation shows that reliability is not one heroic act, but many small sound choices becoming trust and capability."]],
      storyTitle: "李牧守雁门：把力量积到需要的时候", storyTitleEn: "Li Mu at Yanmen: Store Strength for the Necessary Moment", image: "chapter-59-1.png", imageAlt: "李牧守雁门训练备粮择时出击，哆啦A梦说明莫若啬", caption: "啬不是不出手，是让每一分力量用在正处。", captionEn: "Conservation is not inaction; it puts every measure of strength where it matters.",
      story: [["《史记·廉颇蔺相如列传》写李牧守雁门，厚待士卒，训练骑射，谨慎侦察，并命令敌来时先收兵入营。匈奴以为他胆怯，赵王也一度不满。", "The Records of the Grand Historian says Li Mu guarded Yanmen by caring for soldiers, training cavalry, scouting carefully, and initially withdrawing behind prepared defenses. The Xiongnu and even the king of Zhao mistook this for timidity."], ["等兵马、地形与士气都准备成熟，李牧才选择战机，一举稳定边境。前面的不战不是放弃目标，而是不让力量被挑衅切碎。", "When troops, terrain knowledge, and morale were ready, Li Mu chose his moment and stabilized the frontier. Earlier restraint did not abandon the goal; it prevented strength from being fragmented by provocation."]],
      guardTitle: "储备不是无限拖延", guardTitleEn: "Preparation Must Not Become Endless Delay", guard: [["准备若没有判断标准，就会变成不敢开始。真正的啬要同时回答：我们在积累什么？达到什么条件便行动？若局势改变，何时重做判断？", "Preparation without decision criteria becomes fear of beginning. Genuine conservation asks what is being accumulated, what conditions trigger action, and when changing circumstances require a new judgment."]],
      closeTitle: "能长久的力量，通常都留有余地", closeTitleEn: "Enduring Power Usually Preserves a Margin", close: "不把今天用到透支，<br>明天才不是被迫应战。", closeEn: "Do not spend today into exhaustion; tomorrow will not force your hand.", final: "根深，不靠一日猛长；<br><em>力厚，不必逢敌便出。</em>", finalEn: "Deep roots do not grow in one day; stored strength need not answer every provocation.",
      sources: [["《道德经》王弼本", "https://zh.wikisource.org/zh-hans/%E9%81%93%E5%BE%B7%E7%B6%93_%28%E7%8E%8B%E5%BC%BC%E6%9C%AC%29"], ["《史记·廉颇蔺相如列传》", "https://zh.wikisource.org/zh-hant/%E5%8F%B2%E8%A8%98/%E5%8D%B7081"]]
    },
    60: {
      number: "六十", label: "第六十章", hero: "治大国，<br><em>若烹小鲜。</em>", heroEn: "Govern a great state as one cooks a small fish.",
      deck: "少翻动，不是少负责；是让清楚的秩序持续工作。", deckEn: "Turning less is not caring less; it lets a clear order keep working.",
      originalTitle: "夫两不相伤，故德交归焉", originalTitleEn: "When Neither Side Harms the Other, Virtue Returns to Both",
      original: `治大国若烹小鲜。<br>以道莅天下，其鬼不神；非其鬼不神，其神不伤人。<br>非其神不伤人，圣人亦不伤人。<br>夫两不相伤，故德交归焉。`,
      originalEn: "Govern a great state as one cooks a small fish. When the world is approached through the Dao, spirits do not exercise harmful power—not because they cease to exist, but because their power does not injure people. The sage likewise does not injure people. When neither side harms the other, virtue returns to both.",
      explainTitle: "频繁翻动，会把完整的东西弄碎", explainTitleEn: "Constant Turning Breaks What Was Whole",
      explain: [["小鱼细嫩，反复翻动最容易散。国家、组织和家庭也有自己的肌理：规则今天一套明天一套，职责不断重分，人人便把精力用在适应领导的动作，而不是把事情做好。", "A small fish is delicate and falls apart under constant turning. States, organizations, and families also have texture. When rules and roles change constantly, people spend energy adapting to leadership rather than doing the work."], ["“不伤”是本章底线。少干预并不是不管伤害，而是权力先约束自己的扰动，并建立让各种力量互不侵害的边界。", "Non-harm is the chapter’s boundary. Less intervention does not mean ignoring harm. Power first restrains its own disturbance and establishes boundaries within which forces need not injure one another."]],
      storyTitle: "宓子贱治单父：会任人，便不必天天翻动", storyTitleEn: "Mi Zijian Governs Shanfu: Trust People Instead of Turning Everything Daily", image: "chapter-60-1.png", imageAlt: "宓子贱任人治单父，哆啦A梦以烹小鲜说明少翻动", caption: "少翻动，不是少负责；是让合适的人各尽其能。", captionEn: "Turning less is not less responsibility; it lets capable people do their work.",
      story: [["《吕氏春秋·察贤》以宓子贱和巫马期作对照。巫马期每日奔走、亲自处理，宓子贱则弹琴而治。巫马期询问方法，宓子贱说：“我之谓任人，子之谓任力。”", "The Lüshi Chunqiu contrasts Mi Zijian with Wu Maqi. Wu works from dawn to night and handles everything himself; Mi governs while playing the qin. Asked how, Mi replies: “I rely on people; you rely on your own effort.”"], ["任人不是把事情扔出去，而是识人、定责、听取回报，并不因焦虑反复推翻。领导少一次无必要的翻动，系统便多一次形成稳定能力的机会。", "Delegation is not abandonment. It requires choosing people, clarifying responsibility, and hearing reports without overturning work from anxiety. Each unnecessary intervention removed gives the system another chance to develop stable capability."]],
      guardTitle: "少翻动的前提，是锅里没有人在受伤", guardTitleEn: "Turn Less Only When No One Is Being Harmed", guard: [["若出现欺压、失责、腐败或紧急风险，领导必须行动。“若烹小鲜”反对的是为了表现存在而反复折腾，不是要求面对真实伤害仍保持安静。", "When there is abuse, negligence, corruption, or urgent risk, leadership must act. Cooking a small fish opposes repeated meddling performed to display authority; it does not require silence before real harm."]],
      closeTitle: "最好的稳定，不需要领导一直在场", closeTitleEn: "The Best Stability Does Not Require Leadership to Be Everywhere", close: "责任清楚，信息能回来，边界有人守；<br>领导便不必把每件事翻到自己手里。", closeEn: "When responsibility is clear, information returns, and boundaries are guarded, leadership need not turn every matter into its own hands.", final: "少翻一面，<br><em>让秩序自己熟成。</em>", finalEn: "Turn one time less; let order finish cooking.",
      sources: [["《道德经》王弼本", "https://zh.wikisource.org/zh-hans/%E9%81%93%E5%BE%B7%E7%B6%93_%28%E7%8E%8B%E5%BC%BC%E6%9C%AC%29"], ["《吕氏春秋·察贤》", "https://ctext.org/lv-shi-chun-qiu/cha-xian/zh"]]
    },
    58: {
      number: "五八", label: "第五十八章", hero: "祸兮，<br><em>福之所倚。</em>", heroEn: "Misfortune is where fortune leans; fortune is where misfortune hides.",
      deck: "规则越细，事情不一定越好；光越亮，也不必越刺眼。", deckEn: "More detailed rules do not always improve reality, and brighter light need not produce more glare.",
      originalTitle: "其政闷闷，其民淳淳", originalTitleEn: "When Government Is Unobtrusive, People Remain Whole",
      original: `其政闷闷，其民淳淳；其政察察，其民缺缺。<br>祸兮，福之所倚；福兮，祸之所伏。<br>孰知其极？其无正也。<br>正复为奇，善复为妖。人之迷，其日固久。<br><br>是以圣人方而不割，廉而不刿，<br>直而不肆，光而不耀。`,
      originalEn: "When government is unobtrusive, people remain whole; when it is hyper-scrutinizing, people become evasive. Misfortune is where fortune leans; fortune is where misfortune hides. Who knows their limit? The normal turns strange and the good turns monstrous. Thus the sage is square without cutting, upright without wounding, straight without excess, luminous without glare.",
      explainTitle: "控制越密，真实情况越可能躲起来", explainTitleEn: "The Denser the Control, the More Reality May Hide",
      explain: [["规则是必要的，但当检查变成工作的中心，人们便开始优化被检查的表面。汇报越来越漂亮，真实问题却越来越晚才出现；治理越“察察”，系统越擅长把坏消息藏起来。", "Rules are necessary, but when inspection becomes the center of work, people optimize the inspected surface. Reports improve while real problems appear later. The more hyper-scrutinizing governance becomes, the better the system hides bad news."], ["祸福相倚不是说坏事一定变好，而是一个结果会改变下一步的条件。成功可能制造自满，挫折也可能迫使人修正。判断要拉长时间，不能把一个瞬间当作结局。", "The interdependence of fortune and misfortune does not guarantee that bad turns good. Every outcome changes the conditions of the next step. Success may produce complacency; setbacks may compel correction. Judgment must extend through time rather than treating one moment as the end."]],
      storyTitle: "子产不毁乡校：听见批评，治理才看得见", storyTitleEn: "Zichan Keeps the Village Schools: Governance Must Hear Criticism", image: "chapter-58-1.png", imageAlt: "子产不毁乡校并听取百姓议政，哆啦A梦说明其政闷闷", caption: "宽松不是不管，是让真实声音回得来。", captionEn: "Openness is not neglect; it allows truthful voices to return.",
      story: [["《左传·襄公三十一年》记郑人到乡校聚会议政。有人建议子产毁掉乡校，他却说百姓喜欢的就实行，厌恶的就改正；乡校正可以成为老师，为什么要毁？", "The Zuo Commentary records that people of Zheng gathered at village schools to discuss government. When advised to destroy them, Zichan answered that he could practice what people approved and correct what they disliked. The schools could serve as teachers—why destroy them?"], ["子产没有承诺每条批评都照办，而是保留一条让坏消息回到治理中心的路。若这条路被封死，表面会更安静，决策却更盲。", "Zichan did not promise to obey every criticism. He preserved a route by which bad news could return to the center. Close that route, and the surface grows quieter while decisions become blinder."]],
      extra: `<section class="section reveal"><span class="section-kicker">旧图新读</span><h2>从 KPI 到光而不耀</h2><p class="heading-translation" lang="en">From Metrics to Light Without Glare</p><figure class="comic"><img src="chapter-58.png" width="1402" height="1122" loading="lazy" alt="哆啦A梦与大雄用四格解释宽松治理、福祸相倚、指标异化与光而不耀"><figcaption>原有四格保留：规则、转化、指标与分寸。<span class="translation" lang="en">The original four panels remain: rules, reversal, metrics, and proportion.</span></figcaption></figure><p>当指标成为唯一目标，人们会优化指标而不是优化真实目标。圣人的“方、廉、直、光”都有边界：有原则而不伤人，有能力而不炫耀。</p><p class="translation" lang="en">When a metric becomes the sole target, people optimize the metric rather than reality. The sage’s order, integrity, directness, and light all retain boundaries: principle without harm, ability without display.</p></section>`,
      guardTitle: "宽松不是模糊，分寸也不是没有原则", guardTitleEn: "Openness Is Not Vagueness, and Proportion Is Not Principlelessness", guard: [["“方而不割”仍然是方，“直而不肆”仍然是直。老子不是取消底线，而是让底线停止成为伤人和炫耀自己的工具。", "Square without cutting remains square; straight without excess remains straight. Laozi does not erase boundaries. He stops boundaries from becoming instruments of injury and self-display."]],
      closeTitle: "让真实比表面服从更早回来", closeTitleEn: "Let Reality Return Before Surface Obedience Takes Over", close: "听得见批评，问题便有机会停在问题；<br>只听得见赞美，问题迟早会变成祸患。", closeEn: "When criticism can be heard, a problem may remain a problem; when only praise returns, it may become disaster.", final: "有原则，<br><em>却不拿原则伤人。</em>", finalEn: "Keep principles without using them to wound.",
      sources: [["《道德经》王弼本", "https://zh.wikisource.org/zh-hans/%E9%81%93%E5%BE%B7%E7%B6%93_%28%E7%8E%8B%E5%BC%BC%E6%9C%AC%29"], ["《左传·襄公三十一年》", "https://ctext.org/chun-qiu-zuo-zhuan/xiang-gong-san-shi-yi-nian/zh"]]
    },
  };

  const chapter = chapters[document.body.dataset.rangeChapter];
  const root = document.querySelector("#range-chapter-root");
  if (!chapter || !root) return;

  const pairs = (items) => items.map(([cn, en]) => `<p>${cn}</p><p class="translation" lang="en">${en}</p>`).join("");
  const sources = chapter.sources.map(([label, url]) => `<a href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`).join(" · ");

  root.innerHTML = `
    <i class="reading-progress" aria-hidden="true"></i>
    <header class="masthead"><a class="brand" href="index.html"><span>道</span><b>哆啦A梦谈老庄</b></a><a class="back" href="index.html#chapters">返回篇章 ↗</a></header>
    <main>
      <section class="chapter-hero"><span class="big-number">${chapter.number}</span><div>
        <p class="eyebrow">《道德经》${chapter.label}</p><h1>${chapter.hero}</h1>
        <p class="heading-translation hero-heading-translation" lang="en">${chapter.heroEn}</p>
        <blockquote>${chapter.deck}<span class="translation" lang="en">${chapter.deckEn}</span></blockquote>
      </div></section>
      <article class="article">
        <section class="section reveal"><span class="section-kicker">原文</span><h2>${chapter.originalTitle}</h2><p class="heading-translation" lang="en">${chapter.originalTitleEn}</p><p class="source-text">${chapter.original}</p><p class="translation source-translation" lang="en">${chapter.originalEn}</p></section>
        <section class="section reveal"><span class="section-kicker">今译</span><h2>${chapter.explainTitle}</h2><p class="heading-translation" lang="en">${chapter.explainTitleEn}</p>${pairs(chapter.explain)}</section>
        <section class="section reveal"><span class="section-kicker">漫画故事</span><h2>${chapter.storyTitle}</h2><p class="heading-translation" lang="en">${chapter.storyTitleEn}</p><figure class="comic"><img src="${chapter.image}" width="864" height="1821" loading="lazy" alt="${chapter.imageAlt}"><figcaption>${chapter.caption}<span class="translation" lang="en">${chapter.captionEn}</span></figcaption></figure>${pairs(chapter.story)}</section>
        ${chapter.extra || ""}
        <section class="section reveal"><span class="section-kicker">避免误读</span><h2>${chapter.guardTitle}</h2><p class="heading-translation" lang="en">${chapter.guardTitleEn}</p>${pairs(chapter.guard)}</section>
        <section class="section reveal"><span class="section-kicker">本章收束</span><h2>${chapter.closeTitle}</h2><p class="heading-translation" lang="en">${chapter.closeTitleEn}</p><p class="source-text">${chapter.close}</p><p class="translation source-translation" lang="en">${chapter.closeEn}</p></section>
        <section class="section reveal"><span class="section-kicker">参考</span><h2>原典与故事出处</h2><p class="heading-translation" lang="en">Primary Texts and Story Sources</p><p>${sources}</p></section>
      </article>
      <section class="closing"><p>${chapter.final}<span class="translation" lang="en">${chapter.finalEn}</span></p></section>
    </main>
    <footer class="site-footer"><a href="index.html#chapters">← 返回篇章</a><span>${chapter.label} · 完</span><div class="visitor-map" aria-label="访问者地图"></div></footer>`;
})();
